### ISSUE TITLE
Additions to Wiki

### ISSUE THREAD

**Issue by codechippy** [lpollier/battmon#1]
Hi Loic

Just wanted to say many thanks for doing this project.
I have this working on my Sony Aibo ERA7B1 battery (from the Aibo ERS7). This uses the BQ2060.

My aim is to be able to reset the recell I did with new 18650 batteries.

I  have some additions to the Wiki that I would like to add, from the things I learned in making this work.

let me know if you have any issues

Cheers
Codechippy

**Comment by lpollier** [comment]
Hi Chippy,

We have the same goal of repairing ourselves Aibo batteries equipped with bq2040 or bq2060 fuel gauges.

This project is still in progress, especially regarding the methodology for resetting the EEPROM and restarting the GND transistors function, that I'm running out of time to write.

In order to gather your experience and data, I would like to discuss directly via PM. And since github does not allow this service, you can contact me at this address: loic.pollier at protonmail.com

Thanks for your contribution.
Loic

**Comment by codechippy** [comment]
Hi Loic
sorry for late reply, I got sucked into a project that just finished so
have time to pick this back up again.
As I did not hear from you I changed tack a little and moved to an ESP32
option, which needed a little more work
as the 3.3v GPIO pins needed level adustment hardware, but now talks to the
battery.

There were a number of things that I had to resolve on your solution with
the LCD in particular that I thought might be helpful to others.

Code Chippy

**Comment by lpollier** [comment]
Hi CodeChippy,

Well done for porting the Arduino code to the ESP32.
Feel free to add a link to your work if it is on Github.
Have you managed to refill your ERA-7B1 battery?

Loic

**Comment by codechippy** [comment]
Hi
 Sadly
I'm only at the stage of reading the battery status/information.
hope to have some time over the xmas break to start looking at writing to
the battery

Code Chippy

**Comment by lpollier** [comment]
Hi CodeChippy,

Maybe you have now successfully re-celled your Aibo ERA7B1 battery pack. I modified the contents of the README.md file to make it more intuitive to read and will therefore close this issue. Please let me know if you have code or a link to a Git repo that can help other users of bq2060 battery packs.

Loic
